### ISSUE TITLE
看起不来很不错

### ISSUE THREAD

**Issue by xp12047** [zhrust/BXMr#1]
要不是你，我真不知道还有这么有意思的输入法至少看起来是这样的。谢谢😊  
我本身会双拼和86五笔。可最近发现我五笔似乎忘了些想找个更容易记的形码输入法。起初想学学郑码，但没找到适合我的资料。然后今天逛github就搜到了你这个。赶紧fork了(之前有碰到喜欢的项目被删库了)   
我想知道你用的是26键位的表形码还是31键位的。刚搜到居然还有26键位的。只不过我觉得那个26键位的不如31键位看起来好记。  
谢谢，希望没打扰到你😊

**Comment by xp12047** [comment]
另外，后面有时间能不能考虑给生成win64程序。如果可以那就更棒了😬

**Comment by ZoomQuiet** [comment]
@xp12047 是也乎,(￣▽￣)

具体什么品种的俺也不清楚, 因为, 俺使用的 BXM 码表是从 win98se 扒出来,
一路在 Windows NT/ubuntu/macOS 用了24+年...

当初真的是工业制图老师推荐的, 配套拼音效率一直不错 ;-)

当前俺这儿没有 win10 环境, 不过, 这是开源的,
你可以安装 rust 环境, 自己在本地编译一个就好;-)

理论上:

- 有了 cargo+ rustc 之后
- 进入clone 的仓库目录
- cargo build --release 就可以生成一份 win64 的执行代码

不过, 当前 BXMr 是针对俺这儿的码表, 并没兼容其它的...

**Comment by xp12047** [comment]
> @xp12047 是也乎,(￣▽￣)
> 
> 具体什么品种的俺也不清楚, 因为, 俺使用的 BXM 码表是从 win98se 扒出来, 一路在 Windows NT/ubuntu/macOS 用了24+年...
> 
> 当初真的是工业制图老师推荐的, 配套拼音效率一直不错 ;-)
> 
> 当前俺这儿没有 win10 环境, 不过, 这是开源的, 你可以安装 rust 环境, 自己在本地编译一个就好;-)
> 
> 理论上:
> 
> * 有了 cargo+ rustc 之后
> * 进入clone 的仓库目录
> * cargo build --release 就可以生成一份 win64 的执行代码
> 
> 不过, 当前 BXMr 是针对俺这儿的码表, 并没兼容其它的...

额...那你这个码表可以用记事本什么的读出来嘛？我想看下。  
配套拼音？它还能用拼音嘛？那数字键1-5可以打出字偏旁嘛？我看一开始的好像可以打出字的组件比如横就是用1代替，数字1或者/？这个键

**Comment by xp12047** [comment]
我觉得你这个文字表达方式有点像山东或者河南人

**Comment by ZoomQuiet** [comment]
> 我觉得你这个文字表达方式有点像山东或者河南人😬

俺也不知道怎么形成的，虽然本身是兰州人

**Comment by xp12047** [comment]
> > 我觉得你这个文字表达方式有点像山东或者河南人😬
> 
> 俺也不知道怎么形成的，虽然本身是兰州人

你那个键位数字键1-5可以打出汉字嘛？我看另外一个介绍。1代表一笔画那些字的组件。   
我想看下你的键位分布可以嘛？

**Comment by ZoomQuiet** [comment]
> > @xp12047 是也乎,(￣▽￣)
> > 具体什么品种的俺也不清楚, 因为, 俺使用的 BXM 码表是从 win98se 扒出来, 一路在 Windows NT/ubuntu/macOS 用了24+年...
> > 当初真的是工业制图老师推荐的, 配套拼音效率一直不错 ;-)
> > 当前俺这儿没有 win10 环境, 不过, 这是开源的, 你可以安装 rust 环境, 自己在本地编译一个就好;-)
> > 理论上:
> > 
> > * 有了 cargo+ rustc 之后
> > * 进入clone 的仓库目录
> > * cargo build --release 就可以生成一份 win64 的执行代码
> > 
> > 不过, 当前 BXMr 是针对俺这儿的码表, 并没兼容其它的...
> 
> 额...那你这个码表可以用记事本什么的读出来嘛？我想看下。 配套拼音？它还能用拼音嘛？那数字键1-5可以打出字偏旁嘛？我看一开始的好像可以打出字的组件比如横就是用1代替，数字1或者/？这个键

这些需求都是 [RIME \| 中州韻輸入法引擎](https://rime.im/) 提供的能力了...
俺的码表, 早就扒成了 .txt 格式,
现在基本使用 rIME 要求的 .yaml 格式, 可以参考对比:

[ZqBXM/Rime-Squirrel at master · ZoomQuiet/ZqBXM](https://github.com/ZoomQuiet/ZqBXM/tree/master/Rime-Squirrel)

- [bxm\.qim\.txt](https://github.com/ZoomQuiet/ZqBXM/blob/master/Rime-Squirrel/bxm.qim.txt)
- [bxm4zq2mac.dict.yaml](https://github.com/ZoomQuiet/ZqBXM/blob/master/Rime-Squirrel/bxm4zq2mac.dict.yaml)

**Comment by ZoomQuiet** [comment]
> > > 我觉得你这个文字表达方式有点像山东或者河南人😬
> > 
> > 
> > 俺也不知道怎么形成的，虽然本身是兰州人
> 
> 你那个键位数字键1-5可以打出汉字嘛？我看另外一个介绍。1代表一笔画那些字的组件。 我想看下你的键位分布可以嘛？

哦, 俺没这个需求, 另外 BXM 本身要求键码不包含数字, 虽然 rIME 支持定制,

俺用的是标准 87 键盘, 没有专门的数字键区...

**Comment by xp12047** [comment]
> > > > 我觉得你这个文字表达方式有点像山东或者河南人😬
> > > 
> > > 
> > > 俺也不知道怎么形成的，虽然本身是兰州人
> > 
> > 
> > 你那个键位数字键1-5可以打出汉字嘛？我看另外一个介绍。1代表一笔画那些字的组件。 我想看下你的键位分布可以嘛？
> 
> 哦, 俺没这个需求, 另外 BXM 本身要求键码不包含数字, 虽然 rIME 支持定制,
> 
> 俺用的是标准 87 键盘, 没有专门的数字键区...

额，，m旁边的分号？号代表字根嘛？

**Comment by xp12047** [comment]
坦白的讲，俺更搞不明白了。那你帮忙想下。你打师傅的"师"字你的编码是2tss嘛？

**Comment by xp12047** [comment]
可能我的想法是错的。但就我查到的资料。加上上面给的rime那个码表。你这套估计是26键的了。我也查了下关于26键的介绍。我实在佩服那些不符合逻辑的编码规则你是咋记得。比如g键代表那么汉字然后介绍文档还跟它起了个名叫无理编码。其中师傅的师字去掉横用g表示我实在联想不起来。帅我居然忘了去掉横这个字念shuai...用五笔打出来发现的...   
包括你md介绍的那个发明页面都有提到1-5的概念。1-5那里面讲可以按数字也可以用＜>表示...哎

**Comment by ZoomQuiet** [comment]
> 坦白的讲，俺更搞不明白了。那你帮忙想下。你打师傅的"师"字你的编码是2tss嘛？

参考: [BXM\-新编电脑打字七日通\(全民版\)](https://github.com/ZoomQuiet/ZqBXM/raw/master/BXM_%E6%89%93%E5%AD%97%E4%B8%83%E6%97%A5%E9%80%9A_%E5%85%A8%E6%B0%91%E7%89%88.pdf)

gth -> 师
![zshot 2023-03-13 16 56 52](https://user-images.githubusercontent.com/22494/224653415-6e3cf2df-92ef-4bc0-a00c-75405b1371fa.jpg)

表形码, 比较经典的示例是:

epz -> 印

- E -> 象印左半部分
- P -> 象印右半部分
- Z -> 完成拆字后, 就是最后一部分的书写笔顺, 第一笔 横折, 正好也是 Z 的书写方式

所以, 表形码, 基本上就是对自然 英文字母大小写外形进行中文偏旁的合理联想对应...

而且最优秀的是: 绝对坚持以正常书写顺序来进行兑码...

**Comment by xp12047** [comment]
> > 可能我的想法是错的。但就我查到的资料。加上上面给的rime那个码表。你这套估计是26键的了。我也查了下关于26键的介绍。我实在佩服那些不符合逻辑的编码规则你是咋记得。比如g键代表师傅的师字去掉一横，然后介绍文档还跟它起了个名叫无理编码。其中师傅的师字去掉横用g表示我实在联想不起来。居然忘了去掉横这个字念shuai...用五笔打出来发现的... 包括你md介绍的那个发明页面都有提到1-5的概念。1-5那里面讲可以按数字也可以用＜>表示...哎
> 
> 明白了, 当年也只能死记了, 不过, 这种码很少, 好象只有几个... 就是形态上怎么也联想不到具体字母的那几个偏旁...

鞥，我在网上看了基本都改了。现在的表形码都不算表形码。因为很多地方都不搭。  
很多都违背了当时那个女的设计理念。她设计的那个才可唯表形码，因为看上去就能接受也容易记。但就是那一到五个符号我觉得会影响效率。但去掉后的表形码我认为不会记忆太久在有些字根我暂时称它为字根。一定很快忘记。因为太扯了。
